name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g hexo-cli
    - run: npm install hexo-deployer-git --save
    - run: git config --global user.email "lixiang3@outlook.com"
    - run: git config --global user.name "lixiang810"
    - run: hexo deploy
      env:
        CI: true
